//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8825
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckService.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResponse", Namespace="http://schemas.datacontract.org/2004/07/CheckService.Entities")]
    public partial class CheckResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CheckService.Entities.CheckDatabase[] CheckDatabasesField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CheckService.Entities.CheckDatabase[] CheckDatabases
        {
            get
            {
                return this.CheckDatabasesField;
            }
            set
            {
                this.CheckDatabasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckDatabase", Namespace="http://schemas.datacontract.org/2004/07/CheckService.Entities")]
    public partial class CheckDatabase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DateField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private CheckService.Entities.CheckResult ResultField;
        
        private string VersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CheckService.Entities.CheckResult Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResult", Namespace="http://schemas.datacontract.org/2004/07/CheckService.Entities")]
    public enum CheckResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bad = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckPerson", ReplyAction="http://tempuri.org/IService/CheckPersonResponse")]
    CheckService.Entities.CheckResponse CheckPerson(string appName, string hash, string lastName, string firstName, string middleName, string passport);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckCompany", ReplyAction="http://tempuri.org/IService/CheckCompanyResponse")]
    CheckService.Entities.CheckResponse CheckCompany(string appName, string hash, string fullName, string ogrn);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckForeignPerson", ReplyAction="http://tempuri.org/IService/CheckForeignPersonResponse")]
    CheckService.Entities.CheckResponse CheckForeignPerson(string appName, string hash, string lastName, string firstName, string middleName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckForeignCompany", ReplyAction="http://tempuri.org/IService/CheckForeignCompanyResponse")]
    CheckService.Entities.CheckResponse CheckForeignCompany(string appName, string hash, string fullName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CheckService.Entities.CheckResponse CheckPerson(string appName, string hash, string lastName, string firstName, string middleName, string passport)
    {
        return base.Channel.CheckPerson(appName, hash, lastName, firstName, middleName, passport);
    }
    
    public CheckService.Entities.CheckResponse CheckCompany(string appName, string hash, string fullName, string ogrn)
    {
        return base.Channel.CheckCompany(appName, hash, fullName, ogrn);
    }
    
    public CheckService.Entities.CheckResponse CheckForeignPerson(string appName, string hash, string lastName, string firstName, string middleName)
    {
        return base.Channel.CheckForeignPerson(appName, hash, lastName, firstName, middleName);
    }
    
    public CheckService.Entities.CheckResponse CheckForeignCompany(string appName, string hash, string fullName)
    {
        return base.Channel.CheckForeignCompany(appName, hash, fullName);
    }
}
